// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using AwesomeAssertions;
using Xunit;

namespace EricksonLopez.SqlBuilder.Abstractions.Tests;

public class SqlResultTests
{
    [Fact]
    public void SqlResult_RecordEquality_WorksCorrectly()
    {
        // Arrange
        var parameters1 = new Dictionary<string, object?> { { "p0", 1 } };
        var parameters2 = new Dictionary<string, object?> { { "p0", 1 } };
        
        var result1 = new SqlResult("SELECT *", parameters1);
        var result2 = new SqlResult("SELECT *", parameters1);
        var result3 = new SqlResult("SELECT 1", parameters1);
        var result4 = new SqlResult("SELECT *", parameters2);
        
        // Act & Assert
        result1.Sql.Should().Be("SELECT *");
        Assert.Same(parameters1, result1.Parameters);
        
        // Record equality
        result1.Equals(result2).Should().BeTrue();
        result1.Equals((object)result2).Should().BeTrue();
        result1.Equals(null).Should().BeFalse();
        result1.Equals((object?)null).Should().BeFalse();
        (result1 == result2).Should().BeTrue();
        (result1 != result3).Should().BeTrue();
        
        var hash1 = result1.GetHashCode();
        var hash2 = result2.GetHashCode();
        hash2.Should().Be(hash1);
        
        var clone = result1 with { Sql = "SELECT 2" };
        clone.Sql.Should().Be("SELECT 2");
        
        // Test ToString generated by record (PrintMembers)
        var str = result1.ToString();
        str.Should().Contain("SqlResult");
        str.Should().Contain("SELECT *");
        str.Should().Contain("Parameters");
        
        // Test Deconstruct
        var (sql, p) = result1;
        sql.Should().Be("SELECT *");
        p.Should().BeSameAs(parameters1);
    }
}



