<!-- Copyright © Erickson Lopez. MIT License. -->
<Project>
  <Target Name="RemoveIncompatibleAnalyzers" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Analyzer Remove="%(Analyzer.Identity)" Condition="$([System.String]::Copy('%(Analyzer.Identity)').Contains('EricksonLopez.Result.Analyzers'))" />
    </ItemGroup>
  </Target>
</Project>
