<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EricksonLopez.SqlBuilder\EricksonLopez.SqlBuilder.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <PackageTags>$(CommonPackageTags);sqlite;dialect;query-compiler;native-aot</PackageTags>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>


  <ItemGroup>
    <InternalsVisibleTo Include="EricksonLopez.SqlBuilder.Sqlite.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
  </ItemGroup>
</Project>



