// Copyright © Erickson Lopez. MIT License.
using System;

namespace EricksonLopez.SqlBuilder.Abstractions.Metadata;

/// <summary>
/// Specifies flags that describe the behavior and characteristics of a database column.
/// </summary>
[Flags]
public enum ColumnFlags
{
    /// <summary>Indicates that no special column flags are applied.</summary>
    None = 0,
    /// <summary>Indicates that the column forms part of the primary key.</summary>
    PrimaryKey = 1 << 0,
    /// <summary>Indicates that the column is an identity or auto-incrementing column.</summary>
    Identity = 1 << 1,
    /// <summary>Indicates that the column value is always generated by the database.</summary>
    GeneratedAlways = 1 << 2,
    /// <summary>Indicates that the column is a computed or virtual column.</summary>
    Computed = 1 << 3,
    /// <summary>Indicates that the column permits null values.</summary>
    Nullable = 1 << 4
}

