// Copyright © Erickson Lopez. MIT License.
using System;

namespace EricksonLopez.SqlBuilder.Abstractions.Metadata;

/// <summary>
/// Specifies flags that describe the behavior and characteristics of a database column.
/// </summary>
[Flags]
public enum ColumnFlags
{
    /// <summary>No special flags.</summary>
    None = 0,
    /// <summary>The column is part of the primary key.</summary>
    PrimaryKey = 1 << 0,
    /// <summary>The column is an identity or auto-incrementing column.</summary>
    Identity = 1 << 1,
    /// <summary>The column value is always generated by the database (e.g., PostgreSQL GENERATED ALWAYS).</summary>
    GeneratedAlways = 1 << 2,
    /// <summary>The column is a computed column.</summary>
    Computed = 1 << 3,
    /// <summary>The column allows null values.</summary>
    Nullable = 1 << 4
}

