// Copyright © Erickson Lopez. MIT License.
using System;

namespace EricksonLopez.SqlBuilder.Metadata;

/// <summary>
/// Specifies the characteristics of a database column mapped from an entity property.
/// </summary>
[Flags]
public enum ColumnFlags
{
    /// <summary>
    /// Indicates no special characteristics.
    /// </summary>
    None = 0,
    
    /// <summary>
    /// Indicates that the column is part of the primary key.
    /// </summary>
    PrimaryKey = 1 << 0,
    
    /// <summary>
    /// Indicates that the column value is generated by the database upon insertion.
    /// </summary>
    Generated = 1 << 1,
    
    /// <summary>
    /// Indicates that the column allows null values.
    /// </summary>
    Nullable = 1 << 2,
    
    /// <summary>
    /// Indicates that the column is always generated by the database (e.g. Identity).
    /// </summary>
    GeneratedAlways = 1 << 3,
    
    /// <summary>
    /// Indicates that the column is a computed column.
    /// </summary>
    Computed = 1 << 4
}
