// Copyright © Erickson Lopez. MIT License.
using System;
using System.Runtime.CompilerServices;

namespace EricksonLopez.SqlBuilder.Metadata;

/// <summary>
/// Provides efficient and AOT-friendly access to entity metadata generated by the Source Generator.
/// </summary>
public static class EntityMetadataResolver
{
    /// <summary>
    /// Retrieves the static metadata instance for the specified entity type.
    /// </summary>
    /// <remarks>
    /// By utilizing <see cref="IEntityMetadataProvider{T}"/>, the JIT/AOT compiler can completely 
    /// devirtualize and inline this call, achieving a Zero-Cost Abstraction.
    /// </remarks>
    /// <typeparam name="T">The type of the entity whose metadata is being retrieved.</typeparam>
    /// <returns>The <see cref="IEntityMetadata{T}"/> instance associated with the entity.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static IEntityMetadata<T> Get<T>() where T : IEntityMetadataProvider<T>
    {
        return T.Metadata;
    }
}


