// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using EricksonLopez.SqlBuilder.Abstractions;

namespace EricksonLopez.SqlBuilder.Aot;

/// <summary>
/// Provides a reflection-free, NativeAOT-compatible query execution layer over <see cref="IDbConnection"/>
/// using source-generated entity mappers produced by <c>[SqlEntity]</c> and the SQL Builder DSL.
/// </summary>
/// <remarks>
/// <para>
/// Unlike Dapper-based execution, this executor makes no use of runtime IL generation,
/// <c>Reflection.Emit</c>, or <c>DynamicMethod</c>. All entity mapping is delegated to
/// the compile-time <c>Parser</c> class generated by <c>SqlEntityGenerator</c> for each
/// <c>[SqlEntity]</c> type.
/// </para>
/// <para>
/// Use this class as the execution backend when targeting environments that cannot JIT-compile
/// code at runtime: NativeAOT, Blazor WASM (without interpreter), and constrained mobile platforms.
/// </para>
/// </remarks>
public static class AotQueryExecutor
{
    // ─── QueryAsync ───────────────────────────────────────────────────────────

    /// <summary>
    /// Executes the compiled SQL query against the connection and materializes results using a
    /// source-generated entity mapper — with no reflection.
    /// </summary>
    /// <typeparam name="T">
    /// The entity type. Must have a source-generated <c>GetReaderParser()</c> method produced
    /// by <c>SqlEntityGenerator</c>.
    /// </typeparam>
    /// <param name="connection">An open <see cref="IDbConnection"/>.</param>
    /// <param name="result">The compiled SQL + parameters from <see cref="ISqlCompiler.Compile(ISqlQuery)"/>.</param>
    /// <param name="mapper">
    /// A <c>Func&lt;IDataReader, T&gt;</c> factory, typically obtained from
    /// <c>MyEntity.GetReaderParser()</c> or <c>MyEntity.FromReader</c>.
    /// </param>
    /// <param name="transaction">An optional <see cref="IDbTransaction"/>.</param>
    /// <param name="commandTimeout">Optional command timeout in seconds.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>An enumerable of mapped <typeparamref name="T"/> instances.</returns>
    public static async Task<IReadOnlyList<T>> QueryAsync<T>(
        IDbConnection connection,
        SqlResult result,
        Func<IDataReader, T> mapper,
        IDbTransaction? transaction = null,
        int commandTimeout = 30,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(connection);
        ArgumentNullException.ThrowIfNull(mapper);

        using var command = CreateCommand(connection, result, transaction, commandTimeout);
        using var reader = await ExecuteReaderAsync(command, cancellationToken).ConfigureAwait(false);

        var list = new List<T>();
        while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            list.Add(mapper(reader));
        }
        return list;
    }

    /// <summary>
    /// Executes the SQL query and returns the first result, or <see langword="null"/> if none.
    /// </summary>
    /// <typeparam name="T">The entity type.</typeparam>
    /// <param name="connection">An open database connection.</param>
    /// <param name="result">The compiled SQL query and parameters.</param>
    /// <param name="mapper">The row mapper function.</param>
    /// <param name="transaction">An optional database transaction.</param>
    /// <param name="commandTimeout">The command timeout in seconds.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>The first mapped entity, or <see langword="null"/> if the result set is empty.</returns>
    public static async Task<T?> QueryFirstOrDefaultAsync<T>(
        IDbConnection connection,
        SqlResult result,
        Func<IDataReader, T> mapper,
        IDbTransaction? transaction = null,
        int commandTimeout = 30,
        CancellationToken cancellationToken = default)
        where T : class
    {
        ArgumentNullException.ThrowIfNull(connection);
        ArgumentNullException.ThrowIfNull(mapper);

        using var command = CreateCommand(connection, result, transaction, commandTimeout);
        using var reader = await ExecuteReaderAsync(command, CommandBehavior.SingleRow, cancellationToken).ConfigureAwait(false);

        if (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            return mapper(reader);
        }
        return null;
    }

    /// <summary>
    /// Executes the SQL query and returns a single result, throwing if none or more than one are found.
    /// </summary>
    /// <typeparam name="T">The entity type.</typeparam>
    /// <param name="connection">An open database connection.</param>
    /// <param name="result">The compiled SQL query and parameters.</param>
    /// <param name="mapper">The row mapper function.</param>
    /// <param name="transaction">An optional database transaction.</param>
    /// <param name="commandTimeout">The command timeout in seconds.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>The single mapped entity.</returns>
    /// <exception cref="InvalidOperationException">The query returned no results or more than one result</exception>
    public static async Task<T> QuerySingleAsync<T>(
        IDbConnection connection,
        SqlResult result,
        Func<IDataReader, T> mapper,
        IDbTransaction? transaction = null,
        int commandTimeout = 30,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(connection);
        ArgumentNullException.ThrowIfNull(mapper);

        using var command = CreateCommand(connection, result, transaction, commandTimeout);
        using var reader = await ExecuteReaderAsync(command, CommandBehavior.SingleRow, cancellationToken).ConfigureAwait(false);

        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("Query returned no results.");
        }
        var entity = mapper(reader);

        if (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            throw new InvalidOperationException("Query returned more than one result.");
        }
        return entity;
    }

    // ─── ExecuteAsync (non-query) ─────────────────────────────────────────────

    /// <summary>
    /// Executes a non-query SQL statement (INSERT, UPDATE, DELETE) and returns the number of rows affected.
    /// </summary>
    /// <param name="connection">An open database connection.</param>
    /// <param name="result">The compiled SQL query and parameters.</param>
    /// <param name="transaction">An optional database transaction.</param>
    /// <param name="commandTimeout">The command timeout in seconds.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>The number of rows affected.</returns>
    public static async Task<int> ExecuteAsync(
        IDbConnection connection,
        SqlResult result,
        IDbTransaction? transaction = null,
        int commandTimeout = 30,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(connection);

        using var command = CreateCommand(connection, result, transaction, commandTimeout);
        return await ExecuteNonQueryAsync(command, cancellationToken).ConfigureAwait(false);
    }

    // ─── QueryScalarAsync ─────────────────────────────────────────────────────

    /// <summary>
    /// Executes the SQL query and returns the first column of the first row, cast to <typeparamref name="TScalar"/>.
    /// Returns the default value if the result set is empty or the value is <see cref="DBNull"/>.
    /// </summary>
    /// <typeparam name="TScalar">The type of the scalar result.</typeparam>
    /// <param name="connection">An open database connection.</param>
    /// <param name="result">The compiled SQL query and parameters.</param>
    /// <param name="transaction">An optional database transaction.</param>
    /// <param name="commandTimeout">The command timeout in seconds.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>The scalar result value, or <see langword="default"/> if empty.</returns>
    public static async Task<TScalar?> QueryScalarAsync<TScalar>(
        IDbConnection connection,
        SqlResult result,
        IDbTransaction? transaction = null,
        int commandTimeout = 30,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(connection);

        using var command = CreateCommand(connection, result, transaction, commandTimeout);
        using var reader = await ExecuteReaderAsync(command, CommandBehavior.SingleResult | CommandBehavior.SingleRow, cancellationToken).ConfigureAwait(false);

        if (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
        {
            var raw = reader.GetValue(0);
            if (raw is DBNull) return default;
            return (TScalar)raw;
        }
        return default;
    }

    // ─── Private helpers ──────────────────────────────────────────────────────

    private static IDbCommand CreateCommand(
        IDbConnection connection,
        SqlResult result,
        IDbTransaction? transaction,
        int commandTimeout)
    {
        var command = connection.CreateCommand();
        command.CommandText = result.Sql;
        command.CommandTimeout = commandTimeout;
        command.Transaction = transaction;

        if (result.Parameters is not null)
        {
            foreach (var (name, value) in result.Parameters)
            {
                var param = command.CreateParameter();
                param.ParameterName = name;
                param.Value = value ?? DBNull.Value;
                command.Parameters.Add(param);
            }
        }

        return command;
    }

    private static async Task<System.Data.Common.DbDataReader> ExecuteReaderAsync(
        IDbCommand command,
        CancellationToken cancellationToken)
        => await ExecuteReaderAsync(command, CommandBehavior.Default, cancellationToken).ConfigureAwait(false);

    private static async Task<System.Data.Common.DbDataReader> ExecuteReaderAsync(
        IDbCommand command,
        CommandBehavior behavior,
        CancellationToken cancellationToken)
    {
        if (command is System.Data.Common.DbCommand dbCmd)
        {
            return await dbCmd.ExecuteReaderAsync(behavior, cancellationToken).ConfigureAwait(false);
        }

        // Synchronous fallback for ADO providers that don't implement DbCommand
        return (System.Data.Common.DbDataReader)command.ExecuteReader(behavior);
    }

    private static async Task<int> ExecuteNonQueryAsync(
        IDbCommand command,
        CancellationToken cancellationToken)
    {
        if (command is System.Data.Common.DbCommand dbCmd)
        {
            return await dbCmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        // Synchronous fallback
        return command.ExecuteNonQuery();
    }
}




