// Copyright © Erickson Lopez. MIT License.
using System;

namespace EricksonLopez.SqlBuilder.Annotations;

/// <summary>
/// Specifies that a property's value is generated by the database (e.g., identity or default values).
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class DatabaseGeneratedAttribute : Attribute
{
}
