<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" VersionOverride="6.0.4" />
    <PackageReference Include="Dapper" VersionOverride="2.1.79" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Data.SqlClient" VersionOverride="7.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" VersionOverride="17.14.1" />
    <PackageReference Include="Testcontainers.MsSql" VersionOverride="4.13.0" />
    <PackageReference Include="xunit" VersionOverride="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" VersionOverride="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.SqlBuilder\EricksonLopez.SqlBuilder.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.SqlBuilder.SqlServer\EricksonLopez.SqlBuilder.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.SqlBuilder.Dapper\EricksonLopez.SqlBuilder.Dapper.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.SqlBuilder.Testing\EricksonLopez.SqlBuilder.Testing.csproj" />
  </ItemGroup>

</Project>




