<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EricksonLopez.SqlBuilder\EricksonLopez.SqlBuilder.csproj" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <PackageTags>$(CommonPackageTags);sqlserver;mssql;tsql;dialect;query-compiler;native-aot</PackageTags>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI.Unshipped.txt" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EricksonLopez.SqlBuilder.SqlServer.UnitTests" />
  </ItemGroup>

</Project>
