// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using EricksonLopez.SqlBuilder.Abstractions;
using EricksonLopez.SqlBuilder.Abstractions.Metadata;
using EricksonLopez.SqlBuilder.Builders.Bulk;
using Microsoft.Data.SqlClient;

namespace EricksonLopez.SqlBuilder.SqlServer;

/// <summary>
/// Provides a high-performance native bulk INSERT strategy for SQL Server
/// using <see cref="SqlBulkCopy"/> (TDS bulk load protocol).
/// </summary>
/// <remarks>
/// <para>
/// This strategy bypasses parameter-based SQL and streams rows directly
/// to SQL Server via the TDS bulk load protocol, achieving orders-of-magnitude
/// better throughput for large datasets compared to multi-row INSERT statements.
/// </para>
/// <para>
/// Requires a <see cref="SqlConnection"/> from <c>Microsoft.Data.SqlClient</c>.
/// </para>
/// </remarks>
public static class SqlBulkCopyStrategy
{
    /// <summary>
    /// Bulk-inserts a collection of entities into the SQL Server table associated with <typeparamref name="T"/>
    /// using <see cref="SqlBulkCopy"/>.
    /// </summary>
    /// <typeparam name="T">
    /// The entity type. Must implement <see cref="IStaticEntityMetadata{T}"/> (typically generated by the SqlEntity Source Generator).
    /// </typeparam>
    /// <param name="connection">An open <see cref="SqlConnection"/>.</param>
    /// <param name="entities">The entities to insert.</param>
    /// <param name="options">Optional bulk operation options. Defaults to <see cref="BulkOptions.Default"/>.</param>
    /// <param name="transaction">An optional open <see cref="SqlTransaction"/> to enlist.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>
    /// A <see cref="BulkInsertResult{T}"/> with the total number of rows inserted.
    /// When <see cref="BulkOptions.ReturnIdentities"/> is <see langword="true"/>, the original entity
    /// list is returned (identity population requires OUTPUT clause — use <see cref="InsertQuery{T}"/> for that).
    /// </returns>
    /// <exception cref="ArgumentNullException"><paramref name="connection"/> or <paramref name="entities"/> is <see langword="null"/></exception>
    [ExcludeFromCodeCoverage(Justification = "Requires live SQL Server; covered by integration tests.")]
    public static async Task<BulkInsertResult<T>> BulkInsertAsync<T>(
        SqlConnection connection,
        IEnumerable<T> entities,
        BulkOptions? options = null,
        SqlTransaction? transaction = null,
        CancellationToken cancellationToken = default)
        where T : IStaticEntityMetadata<T>
    {
        ArgumentNullException.ThrowIfNull(connection);
        ArgumentNullException.ThrowIfNull(entities);

        options ??= BulkOptions.Default;

        var list = entities as IList<T> ?? new List<T>(entities);
        if (list.Count == 0)
        {
            return BulkInsertResult<T>.WithoutIdentities(0);
        }

        var copyOptions = options.ReturnIdentities
            ? SqlBulkCopyOptions.KeepIdentity
            : SqlBulkCopyOptions.Default;

        using var bulkCopy = new SqlBulkCopy(connection, copyOptions, transaction)
        {
            DestinationTableName = T.TableName,
            BatchSize = options.BatchSize,
            BulkCopyTimeout = options.TimeoutSeconds,
            EnableStreaming = true
        };

        using var reader = new EntityDataReader<T>(list);

        // Map only the non-identity columns
        var columns = T.GetColumns();
        for (int i = 0; i < columns.Length; i++)
        {
            var col = columns[i];
            if (!options.ReturnIdentities && col.HasFlag(ColumnFlags.Identity))
            {
                continue;
            }
            bulkCopy.ColumnMappings.Add(col.Name, col.Name);
        }

        await bulkCopy.WriteToServerAsync(reader, cancellationToken).ConfigureAwait(false);

        return options.ReturnIdentities
            ? new BulkInsertResult<T>(list.Count, list as IReadOnlyList<T> ?? new List<T>(list))
            : BulkInsertResult<T>.WithoutIdentities(list.Count);
    }

    /// <summary>
    /// Bulk-inserts a collection of entities using a generic database connection.
    /// </summary>
    /// <typeparam name="T">The entity type. Must implement <see cref="IStaticEntityMetadata{T}"/>.</typeparam>
    /// <param name="connection">An open database connection (must be a <see cref="SqlConnection"/>).</param>
    /// <param name="entities">The entities to insert.</param>
    /// <param name="options">Optional bulk operation options.</param>
    /// <param name="transaction">An optional database transaction.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>A <see cref="BulkInsertResult{T}"/> with the total number of rows inserted.</returns>
    /// <exception cref="InvalidOperationException"><paramref name="connection"/> is not a <see cref="SqlConnection"/></exception>
    [ExcludeFromCodeCoverage(Justification = "Requires live SQL Server; covered by integration tests.")]
    public static Task<BulkInsertResult<T>> BulkInsertAsync<T>(
        IDbConnection connection,
        IEnumerable<T> entities,
        BulkOptions? options = null,
        IDbTransaction? transaction = null,
        CancellationToken cancellationToken = default)
        where T : IStaticEntityMetadata<T>
    {
        if (connection is not SqlConnection sqlConn)
        {
            throw new InvalidOperationException(
                $"{nameof(SqlBulkCopyStrategy)}.{nameof(BulkInsertAsync)} requires a {nameof(SqlConnection)}.");
        }

        return BulkInsertAsync<T>(sqlConn, entities, options, transaction as SqlTransaction, cancellationToken);
    }
}
