// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using EricksonLopez.SqlBuilder.Abstractions;
using EricksonLopez.SqlBuilder.Abstractions.Metadata;
using EricksonLopez.SqlBuilder.Annotations;

namespace EricksonLopez.SqlBuilder.Testing;

/// <summary>
/// Represents a minimal in-memory entity used exclusively in unit tests to exercise
/// <see cref="ISqlEntity"/> and <see cref="IStaticEntityMetadata{T}"/> contract paths.
/// </summary>
/// <remarks>
/// This type is not intended for production use. It exposes a fixed two-column schema
/// (<c>Id</c>, <c>Name</c>) and is designed to be used as a predictable stand-in when
/// verifying SQL generation, parameter binding, and bulk serialization behavior.
/// </remarks>
public class DummyEntity : ISqlEntity, IStaticEntityMetadata<DummyEntity>
{
    /// <summary>Gets or sets the primary key identifier of the entity.</summary>
    public int Id { get; set; }

    /// <summary>Gets or sets the name value of the entity.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Gets or sets a numeric version value for concurrency testing.</summary>
    public int Version { get; set; }

    /// <summary>Gets or sets a globally unique identifier associated with the entity.</summary>
    public Guid RowGuid { get; set; }

    /// <summary>Gets or sets a value indicating whether the entity is considered active.</summary>
    public bool IsActive { get; set; }

    // ISqlEntity implementation
    /// <inheritdoc/>
    public string GetTableName() => "dummy_entity";

    /// <inheritdoc/>
    public string[] GetColumnNames() => new[] { "id", "name" };

    /// <inheritdoc/>
    public object?[] GetValues() => new object?[] { Id, Name };

    /// <inheritdoc/>
    public string[] GetAllColumnNames() => GetColumnNames();

    /// <inheritdoc/>
    public object?[] GetAllValues() => GetValues();

    /// <inheritdoc/>
    public IReadOnlyDictionary<string, string> GetPropertyMap() => new Dictionary<string, string> { { "Id", "id" }, { "Name", "name" } };

    /// <inheritdoc/>
    public string[] GetIndexedColumns() => Array.Empty<string>();

    // IStaticEntityMetadata<DummyEntity> implementation
    /// <summary>Gets the database table name for this entity type.</summary>
    public static string TableName => "dummy";

    /// <summary>Gets the number of columns defined for this entity type.</summary>
    public static int ColumnCount => 2;

    /// <summary>Returns the column metadata descriptors for the <see cref="DummyEntity"/> schema.</summary>
    /// <returns>A read-only span containing the two column descriptors: <c>Id</c> (primary key) and <c>Name</c>.</returns>
    public static ReadOnlySpan<ColumnMetadata> GetColumns() => new[]
    {
        new ColumnMetadata(0, "Id", ColumnFlags.PrimaryKey),
        new ColumnMetadata(1, "Name", ColumnFlags.None)
    };

    /// <inheritdoc/>
    public static bool IsNull(DummyEntity entity, int columnIndex) => false;

    /// <inheritdoc/>
    public static bool IsDefault(DummyEntity entity, int columnIndex) => false;

    /// <inheritdoc/>
    public static bool AreEqual(DummyEntity entity, DummyEntity snapshot, int columnIndex) => false;

    /// <summary>Returns the column name for the specified zero-based column index.</summary>
    /// <param name="columnIndex">The zero-based column index. <c>0</c> returns <c>"Id"</c>; any other value returns <c>"Name"</c>.</param>
    /// <returns>The column name associated with the specified index.</returns>
    public static string GetColumnName(int columnIndex) => columnIndex == 0 ? "Id" : "Name";

    /// <summary>
    /// Adds the value of the specified column from the given entity to the parameter manager
    /// and returns the generated parameter placeholder.
    /// </summary>
    /// <param name="entity">The entity whose column value is to be bound</param>
    /// <param name="columnIndex">The zero-based index of the column to bind</param>
    /// <param name="parameters">The parameter manager that receives the bound value</param>
    /// <returns>The parameter placeholder string generated by <paramref name="parameters"/>.</returns>
    public static string BindParameter(DummyEntity entity, int columnIndex, IParameterManager parameters)
    {
        return parameters.Add(columnIndex == 0 ? (object)entity.Id : entity.Name);
    }

    /// <summary>
    /// Extracts column value arrays from the given entity span and adds them to the parameter manager
    /// for bulk operations, respecting the active column mask.
    /// </summary>
    /// <param name="entities">The span of entities whose values are extracted</param>
    /// <param name="activeColumns">
    /// A boolean span indicating which columns are active. Index <c>0</c> controls <c>Id</c>;
    /// index <c>1</c> controls <c>Name</c>.
    /// </param>
    /// <param name="parameters">The parameter manager that receives the extracted column arrays</param>
    public static void ExtractColumnArrays(ReadOnlySpan<DummyEntity> entities, ReadOnlySpan<bool> activeColumns, IParameterManager parameters)
    {
        if (activeColumns.Length > 0 && activeColumns[0])
        {
            var arr = new int[entities.Length];
            for (int i = 0; i < entities.Length; i++) arr[i] = entities[i].Id;
            parameters.Add(arr);
        }
        if (activeColumns.Length > 1 && activeColumns[1])
        {
            var arr = new string[entities.Length];
            for (int i = 0; i < entities.Length; i++) arr[i] = entities[i].Name;
            parameters.Add(arr);
        }
    }

    /// <summary>Creates a new <see cref="DummyEntity"/> instance by reading from the specified data reader.</summary>
    /// <param name="reader">The data reader positioned at the current row</param>
    /// <returns>A new <see cref="DummyEntity"/> instance with default values.</returns>
    public static DummyEntity FromReader(System.Data.IDataReader reader) => new DummyEntity();

    /// <summary>Returns a delegate that creates a <see cref="DummyEntity"/> from a data reader row.</summary>
    /// <returns>A factory function that accepts an <see cref="System.Data.IDataReader"/> and returns a new <see cref="DummyEntity"/>.</returns>
    public static Func<System.Data.IDataReader, DummyEntity> GetReaderParser() => (r) => new DummyEntity();
}
