// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Dapper;
using EricksonLopez.SqlBuilder.Abstractions;
using EricksonLopez.SqlBuilder.Dapper;
using EricksonLopez.SqlBuilder.Oracle;
using EricksonLopez.SqlBuilder.Testing.Seeders;
using Oracle.ManagedDataAccess.Client;
using Testcontainers.Oracle;

namespace EricksonLopez.SqlBuilder.Testing.Infrastructure;

/// <summary>
/// Oracle Database XE 21c test fixture backed by Testcontainers.
/// Uses the official Oracle XE image (gvenzl/oracle-xe).
///
/// Behavior:
///   • Docker container is started once per fixture instance
///   • Schema is created under a dedicated user/schema: SQLBUILDER
///   • All tables use Oracle-compatible DDL (NUMBER, VARCHAR2, CLOB)
///   • No BOOLEAN type — uses NUMBER(1,0) / CHAR(1) conventions
///   • SEQUENCES + TRIGGERS for AUTO_INCREMENT equivalent (12c+ uses IDENTITY)
///   • For mutation tests: use transactions rolled back after each test
///
/// Docker image: gvenzl/oracle-xe:21-slim (≈ 2.1 GB, cached after first pull)
/// Startup time: ~60-90 seconds on first run
///
/// NOTE: Oracle requires the system-level SID (XE) and a separate schema user.
/// The container creates a SQLBUILDER user with CONNECT + RESOURCE privileges.
/// </summary>
public sealed class OracleFixture : DatabaseFixture
{
    static OracleFixture()
    {
        global::Dapper.SqlMapper.AddTypeHandler(new OracleBooleanHandler());
    }

    // ─── Container configuration ──────────────────────────────────────────────

    private const string Image    = "gvenzl/oracle-xe:21-slim";
    private const string Password = "S3cure@SqlB!";    // SYS / SYSTEM password
    private const string AppUser  = "SQLBUILDER";      // application schema user
    private const string AppPwd   = "SqlBuilder1";     // ODP.NET requires uppercase

    private OracleContainer? _container;
    private string? _connectionString;

    // ─── DatabaseFixture implementation ───────────────────────────────────────

    public override string ConnectionString =>
        _connectionString ?? throw new InvalidOperationException("Oracle container not started.");

    public override string EngineName => "Oracle";

    public override IDbConnection CreateConnection()
    {
        var conn = new OracleConnection(_connectionString);
        conn.Open();
        return conn;
    }

    public override ISqlCompiler CreateCompiler() => new OracleCompiler();

    // ─── Container lifecycle ──────────────────────────────────────────────────

    protected override async Task StartContainerAsync()
    {
        _container = new OracleBuilder()
            .WithImage(Image)
            .WithPassword(Password)
            .Build();

        // Oracle takes ~60-90s to become healthy — Testcontainers handles the wait
        await _container.StartAsync();

        _connectionString = _container.GetConnectionString();

        // Register compiler globally for OracleConnection
        DapperExtensions.RegisterCompiler<OracleConnection>(() => new OracleCompiler());
        DefaultTypeMap.MatchNamesWithUnderscores = true;
    }

    protected override async Task StopContainerAsync()
    {
        if (_container != null)
        {
            await _container.StopAsync();
            await _container.DisposeAsync();
            _container = null;
        }
    }

    // ─── Schema initialization ────────────────────────────────────────────────

    /// <summary>
    /// Creates the full Oracle 21c schema.
    /// Uses IDENTITY columns (Oracle 12c+), VARCHAR2, NUMBER, CLOB, TIMESTAMP.
    /// All identifiers are uppercase (Oracle default).
    /// </summary>
    protected override async Task InitializeSchemaAsync(System.Data.Common.DbConnection connection)
    {
        foreach (var ddl in GetOracleDdl())
        {
            if (!string.IsNullOrWhiteSpace(ddl))
            {
                await connection.ExecuteAsync(ddl);
            }
        }
    }

    private static IEnumerable<string> GetOracleDdl() =>
    [
        // ─── CATEGORIES ────────────────────────────────────────────────────────
        """
        CREATE TABLE "CATEGORIES" (
            "ID"                 NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "NAME"               VARCHAR2(150) NOT NULL,
            "SLUG"               VARCHAR2(150) NOT NULL UNIQUE,
            "PARENT_CATEGORY_ID" NUMBER            NULL REFERENCES "CATEGORIES"("ID") ON DELETE SET NULL,
            "IS_ACTIVE"          NUMBER(1,0)   DEFAULT 1 NOT NULL,
            "SORT_ORDER"         NUMBER(6)     DEFAULT 0 NOT NULL
        )
        """,

        // ─── TEST_USERS ─────────────────────────────────────────────────────────
        """
        CREATE TABLE "TEST_USERS" (
            "ID"         NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "NAME"       VARCHAR2(250)   NOT NULL,
            "EMAIL"      VARCHAR2(320)       NULL,
            "AGE"        NUMBER(10)      NOT NULL,
            "IS_ACTIVE"  NUMBER(1,0)     DEFAULT 1 NOT NULL,
            "CREATED_AT" TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL
        )
        """,

        // ─── CUSTOMERS ─────────────────────────────────────────────────────────
        """
        CREATE TABLE "CUSTOMERS" (
            "ID"         NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "NAME"       VARCHAR2(250)   NOT NULL,
            "EMAIL"      VARCHAR2(320)   NOT NULL,
            "PHONE"      VARCHAR2(30)        NULL,
            "TAX_ID"     VARCHAR2(50)        NULL,
            "IS_ACTIVE"  NUMBER(1,0)     DEFAULT 1 NOT NULL,
            "CREATED_AT" TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
            "UPDATED_AT" TIMESTAMP(6)        NULL,
            CONSTRAINT "UQ_CUSTOMERS_EMAIL" UNIQUE ("EMAIL")
        )
        """,

        // ─── PRODUCTS ──────────────────────────────────────────────────────────
        """
        CREATE TABLE "PRODUCTS" (
            "ID"          NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CATEGORY_ID" NUMBER          NOT NULL REFERENCES "CATEGORIES"("ID") ON DELETE CASCADE,
            "NAME"        VARCHAR2(250)   NOT NULL,
            "SKU"         VARCHAR2(100)   NOT NULL,
            "DESCRIPTION" CLOB                NULL,
            "PRICE"       NUMBER(18,4)    NOT NULL,
            "COST_PRICE"  NUMBER(18,4)    DEFAULT 0 NOT NULL,
            "STOCK"       NUMBER(10)      DEFAULT 0 NOT NULL,
            "MIN_STOCK"   NUMBER(10)      DEFAULT 0 NOT NULL,
            "IS_ACTIVE"   NUMBER(1,0)     DEFAULT 1 NOT NULL,
            "CREATED_AT"  TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
            "UPDATED_AT"  TIMESTAMP(6)        NULL,
            CONSTRAINT "UQ_PRODUCTS_SKU" UNIQUE ("SKU"),
            CONSTRAINT "CK_PRODUCTS_PRICE" CHECK ("PRICE" >= 0)
        )
        """,

        // ─── ORDERS ────────────────────────────────────────────────────────────
        """
        CREATE TABLE "ORDERS" (
            "ID"              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "CUSTOMER_ID"     NUMBER          NOT NULL REFERENCES "CUSTOMERS"("ID") ON DELETE CASCADE,
            "STATUS"          VARCHAR2(20)    DEFAULT 'pending' NOT NULL,
            "NOTES"           CLOB                NULL,
            "TOTAL_AMOUNT"    NUMBER(18,4)    DEFAULT 0 NOT NULL,
            "TAX_AMOUNT"      NUMBER(18,4)    DEFAULT 0 NOT NULL,
            "DISCOUNT_AMOUNT" NUMBER(18,4)    DEFAULT 0 NOT NULL,
            "CURRENCY"        CHAR(3)         DEFAULT 'USD' NOT NULL,
            "CREATED_AT"      TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
            "CONFIRMED_AT"    TIMESTAMP(6)        NULL,
            "SHIPPED_AT"      TIMESTAMP(6)        NULL,
            "DELIVERED_AT"    TIMESTAMP(6)        NULL,
            "IS_DELETED"      NUMBER(1,0)     DEFAULT 0 NOT NULL,
            "DELETED_AT"      TIMESTAMP(6)        NULL,
            CONSTRAINT "CK_ORDER_STATUS" CHECK ("STATUS" IN ('pending','confirmed','shipped','delivered','cancelled'))
        )
        """,

        // ─── ORDER_ITEMS ───────────────────────────────────────────────────────
        """
        CREATE TABLE "ORDER_ITEMS" (
            "ID"               NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ORDER_ID"         NUMBER        NOT NULL REFERENCES "ORDERS"("ID") ON DELETE CASCADE,
            "PRODUCT_ID"       NUMBER        NOT NULL REFERENCES "PRODUCTS"("ID") ON DELETE CASCADE,
            "QUANTITY"         NUMBER(10)    NOT NULL,
            "UNIT_PRICE"       NUMBER(18,4)  DEFAULT 0 NOT NULL,
            "DISCOUNT_PERCENT" NUMBER(5,2)   DEFAULT 0 NOT NULL,
            "TOTAL_PRICE"      NUMBER(18,4)  DEFAULT 0 NOT NULL,
            "NOTES"            VARCHAR2(500)     NULL,
            CONSTRAINT "CK_OI_QTY" CHECK ("QUANTITY" > 0)
        )
        """,

        // ─── USERS ─────────────────────────────────────────────────────────────
        """
        CREATE TABLE "USERS" (
            "ID"                    NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "USERNAME"              VARCHAR2(100)   NOT NULL,
            "EMAIL"                 VARCHAR2(320)   NOT NULL,
            "PASSWORD_HASH"         VARCHAR2(250)   NOT NULL,
            "FIRST_NAME"            VARCHAR2(100)       NULL,
            "LAST_NAME"             VARCHAR2(100)       NULL,
            "IS_ACTIVE"             NUMBER(1,0)     DEFAULT 1 NOT NULL,
            "EMAIL_VERIFIED"        NUMBER(1,0)     DEFAULT 0 NOT NULL,
            "CREATED_AT"            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
            "LAST_LOGIN_AT"         TIMESTAMP(6)        NULL,
            "LOCKED_UNTIL"          TIMESTAMP(6)        NULL,
            "FAILED_LOGIN_ATTEMPTS" NUMBER(3)       DEFAULT 0 NOT NULL,
            CONSTRAINT "UQ_USERS_USERNAME" UNIQUE ("USERNAME"),
            CONSTRAINT "UQ_USERS_EMAIL"    UNIQUE ("EMAIL")
        )
        """,

        // ─── ROLES ─────────────────────────────────────────────────────────────
        """
        CREATE TABLE "ROLES" (
            "ID"          NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "NAME"        VARCHAR2(100)   NOT NULL,
            "DESCRIPTION" CLOB                NULL,
            "PERMISSIONS" CLOB                NOT NULL,
            "IS_SYSTEM"   NUMBER(1,0)     DEFAULT 0 NOT NULL,
            "CREATED_AT"  TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT "UQ_ROLES_NAME" UNIQUE ("NAME")
        )
        """,

        // ─── USER_ROLES ────────────────────────────────────────────────────────
        """
        CREATE TABLE "USER_ROLES" (
            "USER_ID"             NUMBER       NOT NULL REFERENCES "USERS"("ID") ON DELETE CASCADE,
            "ROLE_ID"             NUMBER       NOT NULL REFERENCES "ROLES"("ID") ON DELETE CASCADE,
            "ASSIGNED_AT"         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
            "ASSIGNED_BY_USER_ID" NUMBER           NULL,
            CONSTRAINT "PK_USER_ROLES" PRIMARY KEY ("USER_ID", "ROLE_ID")
        )
        """,

        // ─── INVOICES ──────────────────────────────────────────────────────────
        """
        CREATE TABLE "INVOICES" (
            "ID"              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ORDER_ID"        NUMBER          NOT NULL REFERENCES "ORDERS"("ID") ON DELETE CASCADE,
            "INVOICE_NUMBER"  VARCHAR2(50)    NOT NULL,
            "STATUS"          VARCHAR2(20)    DEFAULT 'draft' NOT NULL,
            "SUBTOTAL_AMOUNT" NUMBER(18,4)    DEFAULT 0 NOT NULL,
            "TAX_AMOUNT"      NUMBER(18,4)    DEFAULT 0 NOT NULL,
            "TOTAL_AMOUNT"    NUMBER(18,4)    DEFAULT 0 NOT NULL,
            "PAID_AMOUNT"     NUMBER(18,4)    DEFAULT 0 NOT NULL,
            "CURRENCY"        CHAR(3)         DEFAULT 'USD' NOT NULL,
            "ISSUED_AT"       TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
            "DUE_AT"          TIMESTAMP(6)    NOT NULL,
            "PAID_AT"         TIMESTAMP(6)        NULL,
            "NOTES"           CLOB                NULL,
            CONSTRAINT "UQ_INVOICE_NUMBER" UNIQUE ("INVOICE_NUMBER")
        )
        """,

        // ─── PAYMENTS ──────────────────────────────────────────────────────────
        """
        CREATE TABLE "PAYMENTS" (
            "ID"               NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "INVOICE_ID"       NUMBER          NOT NULL REFERENCES "INVOICES"("ID") ON DELETE CASCADE,
            "AMOUNT"           NUMBER(18,4)    NOT NULL,
            "METHOD"           VARCHAR2(30)    NOT NULL,
            "STATUS"           VARCHAR2(20)    DEFAULT 'pending' NOT NULL,
            "TRANSACTION_REF"  VARCHAR2(200)       NULL,
            "GATEWAY_RESPONSE" CLOB                NULL,
            "PAID_AT"          TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
            "REFUNDED_AT"      TIMESTAMP(6)        NULL,
            "REFUNDED_AMOUNT"  NUMBER(18,4)        NULL
        )
        """,

        // ─── AUDIT_LOGS ────────────────────────────────────────────────────────
        """
        CREATE TABLE "AUDIT_LOGS" (
            "ID"             NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "ENTITY_NAME"    VARCHAR2(100)   NOT NULL,
            "ENTITY_ID"      VARCHAR2(100)   NOT NULL,
            "ACTION"         VARCHAR2(10)    NOT NULL,
            "OLD_VALUES"     CLOB                NULL,
            "NEW_VALUES"     CLOB                NULL,
            "CHANGED_FIELDS" CLOB                NULL,
            "USER_ID"        NUMBER              NULL,
            "IP_ADDRESS"     VARCHAR2(45)        NULL,
            "USER_AGENT"     VARCHAR2(500)       NULL,
            "TIMESTAMP"      TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
            "CORRELATION_ID" VARCHAR2(50)        NULL,
            CONSTRAINT "CK_AUDIT_ACTION" CHECK ("ACTION" IN ('INSERT','UPDATE','DELETE'))
        )
        """
    ];

    // ─── Data seeding ─────────────────────────────────────────────────────────

    protected override async Task SeedCoreDataAsync(System.Data.Common.DbConnection connection)
    {
        foreach (var cat in TestDataSeeder.Categories())
        {
            // Oracle IDENTITY: skip ID, let the sequence generate it
            // But for deterministic tests we override with INSERT OVERRIDING SYSTEM VALUE
            await connection.ExecuteAsync(
                """
                INSERT INTO "CATEGORIES" ("ID","NAME","SLUG","PARENT_CATEGORY_ID","IS_ACTIVE","SORT_ORDER")
                VALUES (:Id, :Name, :Slug, :ParentCategoryId, :IsActive, :SortOrder)
                """,
                new { cat.Id, cat.Name, cat.Slug, cat.ParentCategoryId, IsActive = cat.IsActive ? 1 : 0, cat.SortOrder });
        }
    }

    protected override async Task SeedTestDataAsync(System.Data.Common.DbConnection connection)
    {
        var dataset = Data;

        using var tx = connection.BeginTransaction();

        // Customers
        foreach (var c in dataset.Customers)
        {
            await connection.ExecuteAsync(
                """
                INSERT INTO "CUSTOMERS" ("ID","NAME","EMAIL","PHONE","TAX_ID","IS_ACTIVE","CREATED_AT","UPDATED_AT")
                VALUES (:Id, :Name, :Email, :Phone, :TaxId, :IsActive, :CreatedAt, :UpdatedAt)
                """,
                new { c.Id, c.Name, c.Email, c.Phone, c.TaxId, IsActive = c.IsActive ? 1 : 0,
                      c.CreatedAt, c.UpdatedAt },
                tx);
        }

        // Products
        foreach (var p in dataset.Products)
        {
            await connection.ExecuteAsync(
                """
                INSERT INTO "PRODUCTS" ("ID","CATEGORY_ID","NAME","SKU","DESCRIPTION","PRICE","COST_PRICE","STOCK","MIN_STOCK","IS_ACTIVE","CREATED_AT","UPDATED_AT")
                VALUES (:Id, :CategoryId, :Name, :Sku, :Description, :Price, :CostPrice, :Stock, :MinStock, :IsActive, :CreatedAt, :UpdatedAt)
                """,
                new { p.Id, p.CategoryId, p.Name, p.Sku, p.Description, p.Price, p.CostPrice, p.Stock, p.MinStock,
                      IsActive = p.IsActive ? 1 : 0, p.CreatedAt, p.UpdatedAt },
                tx);
        }

        // Orders
        foreach (var o in dataset.Orders)
        {
            await connection.ExecuteAsync(
                """
                INSERT INTO "ORDERS" ("ID","CUSTOMER_ID","STATUS","NOTES","TOTAL_AMOUNT","TAX_AMOUNT","DISCOUNT_AMOUNT","CURRENCY","CREATED_AT","CONFIRMED_AT","SHIPPED_AT","DELIVERED_AT","IS_DELETED","DELETED_AT")
                VALUES (:Id, :CustomerId, :Status, :Notes, :TotalAmount, :TaxAmount, :DiscountAmount, :Currency, :CreatedAt, :ConfirmedAt, :ShippedAt, :DeliveredAt, :IsDeleted, :DeletedAt)
                """,
                new { o.Id, o.CustomerId, o.Status, o.Notes, o.TotalAmount, o.TaxAmount, o.DiscountAmount,
                      o.Currency, o.CreatedAt, o.ConfirmedAt, o.ShippedAt, o.DeliveredAt, IsDeleted = o.IsDeleted ? 1 : 0, o.DeletedAt },
                tx);
        }

        // Order Items
        foreach (var oi in dataset.OrderItems)
        {
            await connection.ExecuteAsync(
                """
                INSERT INTO "ORDER_ITEMS" ("ID","ORDER_ID","PRODUCT_ID","QUANTITY","UNIT_PRICE","DISCOUNT_PERCENT","TOTAL_PRICE","NOTES")
                VALUES (:Id, :OrderId, :ProductId, :Quantity, :UnitPrice, :DiscountPercent, :TotalPrice, :Notes)
                """,
                new { oi.Id, oi.OrderId, oi.ProductId, oi.Quantity, oi.UnitPrice, oi.DiscountPercent, oi.TotalPrice, oi.Notes },
                tx);
        }

        // Advance sequences to avoid ORA-00001 after explicit ID inserts
        var tablesToReset = new[] { "CATEGORIES", "CUSTOMERS", "PRODUCTS", "ORDERS", "ORDER_ITEMS" };
        foreach (var table in tablesToReset)
        {
            await connection.ExecuteAsync($"""ALTER TABLE "{table}" MODIFY "ID" GENERATED BY DEFAULT AS IDENTITY (START WITH 1000)""", transaction: tx);
        }

        tx.Commit();
    }
}
