// Copyright © Erickson Lopez. MIT License.
using EricksonLopez.SqlBuilder.Abstractions.Nodes;
using System;
using EricksonLopez.SqlBuilder.Abstractions;

namespace EricksonLopez.SqlBuilder;

/// <summary>
/// Provides extension methods for generating UPDATE statements based on entity state differences.
/// </summary>
public static class DiffUpdateExtensions
{
    /// <summary>
    /// Applies SET assignments to the UPDATE query by comparing the original and current state of the entity.
    /// Only properties that have changed will generate a SET assignment.
    /// </summary>
    /// <remarks>
    /// Utilizes the <see cref="EricksonLopez.SqlBuilder.Annotations.ISqlEntity"/> interface 
    /// generated by the source generator to perform a reflection-free comparison.
    /// </remarks>
    /// <typeparam name="T">The type of the entity to update.</typeparam>
    /// <param name="builder">The update query builder to configure.</param>
    /// <param name="originalEntity">The original state of the entity before any modifications.</param>
    /// <param name="currentEntity">The current state of the entity containing the modifications.</param>
    /// <returns>An <see cref="IUpdateWhereBuilder{T}"/> instance configured with the detected changes.</returns>
    /// <exception cref="InvalidOperationException">
    /// No changes are detected between the original and current entity, 
    /// the builder is not of type <see cref="UpdateQuery{T}"/>, 
    /// or <typeparamref name="T"/> does not implement <see cref="EricksonLopez.SqlBuilder.Annotations.ISqlEntity"/>
    /// </exception>
    public static IUpdateWhereBuilder<T> ApplyDiff<T>(
        this IUpdateSetBuilder<T> builder, 
        T originalEntity, 
        T currentEntity) where T : class, new()
    {
        var query = builder as UpdateQuery<T>;
        if (query != null)
        {
            var origSqlEntity = originalEntity as EricksonLopez.SqlBuilder.Annotations.ISqlEntity;
            var currSqlEntity = currentEntity as EricksonLopez.SqlBuilder.Annotations.ISqlEntity;
            if (origSqlEntity != null && currSqlEntity != null)
            {
                var columns = currSqlEntity.GetColumnNames();
                var origValues = origSqlEntity.GetValues();
                var currValues = currSqlEntity.GetValues();
                
                if (columns.Length != origValues.Length || columns.Length != currValues.Length)
                {
                    throw new InvalidOperationException($"Entity {typeof(T).Name} metadata mismatch: GetColumnNames() returned {columns.Length} items, but GetValues() returned {origValues.Length} and {currValues.Length}. They must match.");
                }
                
                bool hasChanges = false;
                for (int i = 0; i < columns.Length; i++)
                {
                    var origVal = origValues[i];
                    var currVal = currValues[i];
                    
                    if (!object.Equals(origVal, currVal))
                    {
                        query = query.AddNode(new SetNode(columns[i], currVal));
                        hasChanges = true;
                    }
                }
                
                if (!hasChanges)
                {
                    throw new InvalidOperationException("No changes detected between original and current entity.");
                }
                
                return query;
            }
            throw new InvalidOperationException($"Entity {typeof(T).Name} does not implement ISqlEntity. Please ensure EricksonLopez.SqlBuilder.SourceGenerators is added and the entity is marked with [SqlEntity].");
        }
        
        throw new InvalidOperationException("Builder is not of type UpdateQuery<T>.");
    }
}


